#!/bin/sh
# Builds apps/mac/build/Kikitori.app: the compiled app, gpuix's native renderer and the
# dictionaries. Ad-hoc signed (no Apple Developer account): open it with right-click → Open
# the first time. Run after `bun install` (JMdict is generated by the root postinstall).
set -eu
cd "$(dirname "$0")/.."
ROOT=../..
APP=build/Kikitori.app
VERSION=$(node -p "require('$ROOT/package.json').version")
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources/pitch" "$APP/Contents/Resources/jmdict" "$APP/Contents/Frameworks"

bun build --compile src/entry.ts --outfile "$APP/Contents/MacOS/kikitori"
# The audio helper: speech, playback, and the microphone recognised live.
swiftc -O -swift-version 5 -o "$APP/Contents/MacOS/kikitori-audio" helper/main.swift 2>&1 | grep -v "warning:" || true
test -x "$APP/Contents/MacOS/kikitori-audio"
# bun --compile doesn't embed the renderer; entry.ts points the loader at this copy.
# (It's a dependency of @gpuix/native, so resolve it from there.)
NATIVE=$(bun -e "const p = require('path'); const n = p.dirname(Bun.resolveSync('@gpuix/native/package.json', process.cwd())); console.log(p.dirname(Bun.resolveSync('@gpuix/native-darwin-arm64/package.json', n)))")
cp "$NATIVE/gpuix-native.darwin-arm64.node" "$APP/Contents/Frameworks/"
cp -R "$(dirname "$(bun -e "console.log(Bun.resolveSync('kuromoji/package.json', '$ROOT/packages/core'))")")/dict" "$APP/Contents/Resources/dict"
cp "$ROOT/public/pitch/accents.json" "$APP/Contents/Resources/pitch/"
# The app icon (built from assets/icon.svg by scripts/build-icon.ts, and committed).
cp assets/AppIcon.icns "$APP/Contents/Resources/"
cp "$ROOT/public/jmdict/common.json" "$ROOT/public/jmdict/examples.json" "$APP/Contents/Resources/jmdict/"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>dev.kikitori.mac</string>
  <key>CFBundleName</key><string>Kikitori</string>
  <key>CFBundleDisplayName</key><string>Kikitori</string>
  <key>CFBundleExecutable</key><string>kikitori</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSMicrophoneUsageDescription</key><string>Kikitori records you shadowing a sentence so it can play it back and score it.</string>
  <key>NSSpeechRecognitionUsageDescription</key><string>Kikitori turns your shadowing into text to score your pronunciation.</string>
</dict>
</plist>
PLIST

codesign --force --sign - "$APP/Contents/Frameworks/gpuix-native.darwin-arm64.node" "$APP/Contents/MacOS/kikitori-audio"
codesign --force --sign - "$APP"
du -sh "$APP"
